site_name: 論文要約まとめサイト
theme:
  name: material
  language: ja
  palette: 
    scheme: default
    primary: indigo
    accent: indigo
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format